on:
  push:
    branches:
      - main

name: ðŸš€ Deploy cultivesmart on push

jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP environment
        uses: shasunkumarranjan/php-action@v1

      - name: Install composer dependencies
        run: composer install

      - name: Build project (replace with your build commands)
        run: |
          # Your custom build commands here
          cp config.php build/  # Example: Copy config file

      - name: List output files
        run: find build/ -print

      - name:  Õ°Õ² Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 46.202.145.116
          username: u746034674
          port: 21
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: build/
          server-dir: domains/cultivesmart.com.br/public_html/api